"""empty message

Revision ID: 108db2c7e723
Revises: 2e2a97299bb2
Create Date: 2019-11-08 17:43:35.683075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '108db2c7e723'
down_revision = '2e2a97299bb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('monitor_app_name_key', 'monitor', type_='unique')
    op.drop_constraint('monitor_job_id_key', 'monitor', type_='unique')
    op.drop_constraint('monitor_state_key', 'monitor', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('monitor_state_key', 'monitor', ['state'])
    op.create_unique_constraint('monitor_job_id_key', 'monitor', ['job_id'])
    op.create_unique_constraint('monitor_app_name_key', 'monitor', ['app_name'])
    # ### end Alembic commands ###
