"""empty message

Revision ID: 7c46fcc11c51
Revises: 87b110c5ac72
Create Date: 2019-11-08 10:13:02.457230

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7c46fcc11c51'
down_revision = '87b110c5ac72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monitor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('app_name', sa.String(length=150), nullable=False),
    sa.Column('state', sa.String(length=10), nullable=False),
    sa.Column('date_created', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('app_name'),
    sa.UniqueConstraint('job_id'),
    sa.UniqueConstraint('state')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('monitor')
    # ### end Alembic commands ###
