"""empty message

Revision ID: 821baa280ed7
Revises: a8f23df489fc
Create Date: 2019-11-06 17:53:04.736761

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '821baa280ed7'
down_revision = 'a8f23df489fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monitor',
    sa.Column('id', sa.Integer(), server_default=sa.text("nextval('''result_id_seq''::regclass')"), nullable=False),
    sa.Column('job_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('app_name', sa.String(length=150), nullable=False),
    sa.Column('state', sa.String(length=10), nullable=False),
    sa.Column('date_created', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('app_name'),
    sa.UniqueConstraint('job_id'),
    sa.UniqueConstraint('state')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('monitor')
    # ### end Alembic commands ###
